# Generated by Django 2.2.15 on 2020-08-07 09:32

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_vendor_reviews', '0002_rating-opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviewoption',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_reviews_option', to='shuup.Shop', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='vendorreviewoptiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup_vendor_reviews.VendorReviewOption'),
        ),
    ]
